import { Schedule, Comment } from "@/lib/types"

// mock schedules for the feed
// each has events, reactions, author, etc.
export const mockSchedules: Schedule[] = [
  {
    id: "1",
    title: "Fall 2024 CS Heavy Load",
    term: "Fall 2024",
    events: [
      {
        title: "Data Structures & Algorithms",
        day_of_week: 1,
        start_time: "09:00",
        end_time: "10:30",
        location: "CS Building 101",
        color: "#3B82F6",
      },
      {
        title: "Computer Architecture",
        day_of_week: 1,
        start_time: "14:00",
        end_time: "15:30",
        location: "CS Building 203",
        color: "#10B981",
      },
      {
        title: "Database Systems",
        day_of_week: 3,
        start_time: "10:00",
        end_time: "11:30",
        location: "CS Building 105",
        color: "#F59E0B",
      },
      {
        title: "Software Engineering",
        day_of_week: 4,
        start_time: "13:00",
        end_time: "15:30",
        location: "CS Building 210",
        color: "#EF4444",
      },
      {
        title: "Machine Learning",
        day_of_week: 5,
        start_time: "09:00",
        end_time: "10:30",
        location: "AI Lab 301",
        color: "#8B5CF6",
      },
    ],
    author: { id: "user1", handle: "mint-otter-42" },
    reactions: { up: 156, down: 12, mine: null },
    comments_count: 23,
    created_at: "2024-01-15T10:00:00Z",
    school: "State University",
    year: "2024",
    major: "Computer Science",
  },
  {
    id: "2",
    title: "Balanced Engineering Spring",
    term: "Spring 2024",
    events: [
      {
        title: "Thermodynamics",
        day_of_week: 2,
        start_time: "08:00",
        end_time: "09:30",
        location: "Engineering Hall 201",
        color: "#DC2626",
      },
      {
        title: "Fluid Mechanics Lab",
        day_of_week: 2,
        start_time: "14:00",
        end_time: "17:00",
        location: "Lab Building A-103",
        color: "#059669",
      },
      {
        title: "Materials Science",
        day_of_week: 4,
        start_time: "10:00",
        end_time: "11:30",
        location: "Materials Lab",
        color: "#7C3AED",
      },
      {
        title: "Engineering Ethics",
        day_of_week: 5,
        start_time: "13:00",
        end_time: "14:30",
        location: "Humanities 150",
        color: "#0891B2",
      },
    ],
    author: { id: "user2", handle: "clever-fox-17" },
    reactions: { up: 89, down: 5, mine: "up" },
    comments_count: 15,
    created_at: "2024-01-14T14:30:00Z",
    school: "Tech Institute",
    year: "2024",
    major: "Mechanical Engineering",
  },
  {
    id: "3",
    title: "Business Major Dream Schedule",
    term: "Fall 2024",
    events: [
      {
        title: "Corporate Finance",
        day_of_week: 1,
        start_time: "11:00",
        end_time: "12:30",
        location: "Business Center 320",
        color: "#059669",
      },
      {
        title: "Marketing Strategy",
        day_of_week: 3,
        start_time: "09:00",
        end_time: "10:30",
        location: "Business Center 205",
        color: "#DC2626",
      },
      {
        title: "Operations Management",
        day_of_week: 3,
        start_time: "14:00",
        end_time: "15:30",
        location: "Business Center 110",
        color: "#7C3AED",
      },
      {
        title: "Business Analytics",
        day_of_week: 5,
        start_time: "10:00",
        end_time: "11:30",
        location: "Computer Lab 5",
        color: "#0891B2",
      },
    ],
    author: { id: "user3", handle: "bright-eagle-88" },
    reactions: { up: 134, down: 8, mine: "down" },
    comments_count: 31,
    created_at: "2024-01-13T09:15:00Z",
    school: "State University",
    year: "2024",
    major: "Business Administration",
  },
  {
    id: "4",
    title: "Pre-Med Nightmare Schedule",
    term: "Spring 2024",
    events: [
      {
        title: "Organic Chemistry II",
        day_of_week: 1,
        start_time: "08:00",
        end_time: "09:30",
        location: "Chemistry Building 301",
        color: "#EF4444",
      },
      {
        title: "Organic Chem Lab",
        day_of_week: 1,
        start_time: "14:00",
        end_time: "17:00",
        location: "Chemistry Lab 201",
        color: "#EF4444",
      },
      {
        title: "Physics II",
        day_of_week: 2,
        start_time: "10:00",
        end_time: "11:30",
        location: "Physics Building 105",
        color: "#3B82F6",
      },
      {
        title: "Biochemistry",
        day_of_week: 4,
        start_time: "09:00",
        end_time: "10:30",
        location: "Biology Building 220",
        color: "#10B981",
      },
      {
        title: "Anatomy & Physiology",
        day_of_week: 5,
        start_time: "13:00",
        end_time: "15:30",
        location: "Medical Sciences 115",
        color: "#F59E0B",
      },
    ],
    author: { id: "user4", handle: "determined-shark-23" },
    reactions: { up: 67, down: 34, mine: null },
    comments_count: 42,
    created_at: "2024-01-12T16:45:00Z",
    school: "City College",
    year: "2023",
    major: "Biology",
  },
  {
    id: "5",
    title: "Psychology Major Chill Vibes",
    term: "Fall 2024",
    events: [
      {
        title: "Cognitive Psychology",
        day_of_week: 2,
        start_time: "11:00",
        end_time: "12:30",
        location: "Psychology Building 201",
        color: "#8B5CF6",
      },
      {
        title: "Research Methods",
        day_of_week: 3,
        start_time: "13:00",
        end_time: "14:30",
        location: "Psychology Building 105",
        color: "#059669",
      },
      {
        title: "Abnormal Psychology",
        day_of_week: 4,
        start_time: "10:00",
        end_time: "11:30",
        location: "Liberal Arts 230",
        color: "#DC2626",
      },
    ],
    author: { id: "user5", handle: "zen-panda-91" },
    reactions: { up: 203, down: 7, mine: "up" },
    comments_count: 18,
    created_at: "2024-01-11T11:20:00Z",
    school: "Community College",
    year: "2024",
    major: "Psychology",
  },
]

// mock comments keyed by schedule id
export const mockComments: Record<string, Comment[]> = {
  "1": [
    {
      id: "c1",
      body: "this schedule is absolutely brutal! how do you manage 5 cs courses in one semester? respect! 💪",
      created_at: "2024-01-15T12:30:00Z",
      author: { id: "user6", handle: "code-ninja-55" },
      schedule_id: "1",
    },
    {
      id: "c2",
      body: "machine learning on friday morning is rough but professor johnson makes it worth it. great class selection!",
      created_at: "2024-01-15T14:15:00Z",
      author: { id: "user7", handle: "data-wizard-22" },
      schedule_id: "1",
    },
    {
      id: "c3",
      body: "i tried a similar load last semester and burned out by week 10. make sure to take care of yourself!",
      created_at: "2024-01-15T16:45:00Z",
      author: { id: "user8", handle: "wise-owl-77" },
      schedule_id: "1",
    },
    {
      id: "c4",
      body: "database systems with software engineering is a killer combo. you'll learn so much about system design!",
      created_at: "2024-01-16T09:20:00Z",
      author: { id: "user9", handle: "system-architect-12" },
      schedule_id: "1",
    },
  ],
  "2": [
    {
      id: "c5",
      body: "love the balance here! engineering ethics is such an underrated course. highly recommend!",
      created_at: "2024-01-14T15:00:00Z",
      author: { id: "user10", handle: "ethical-engineer-44" },
      schedule_id: "2",
    },
    {
      id: "c6",
      body: "that 3-hour fluid mechanics lab on tuesday is going to be intense. hope you like getting messy! 😅",
      created_at: "2024-01-14T17:30:00Z",
      author: { id: "user11", handle: "fluid-dynamics-pro" },
      schedule_id: "2",
    },
    {
      id: "c7",
      body: "materials science is fascinating but the workload is no joke. start the problem sets early!",
      created_at: "2024-01-15T08:45:00Z",
      author: { id: "user12", handle: "materials-master-33" },
      schedule_id: "2",
    },
  ],
  "3": [
    {
      id: "c8",
      body: "this is exactly the schedule i'm aiming for! how's professor martinez for corporate finance?",
      created_at: "2024-01-13T10:30:00Z",
      author: { id: "user13", handle: "future-cfo-21" },
      schedule_id: "3",
    },
    {
      id: "c9",
      body: "marketing strategy changed my whole perspective on business. you're in for a treat!",
      created_at: "2024-01-13T13:15:00Z",
      author: { id: "user14", handle: "marketing-maven-67" },
      schedule_id: "3",
    },
    {
      id: "c10",
      body: "business analytics in the computer lab is so much better than lecture hall. great scheduling!",
      created_at: "2024-01-13T16:20:00Z",
      author: { id: "user15", handle: "analytics-ace-89" },
      schedule_id: "3",
    },
  ],
  "4": [
    {
      id: "c11",
      body: "organic chem ii + lab on the same day? you're a warrior! i split mine across different semesters 😵",
      created_at: "2024-01-12T18:00:00Z",
      author: { id: "user16", handle: "pre-med-survivor" },
      schedule_id: "4",
    },
    {
      id: "c12",
      body: "this schedule is giving me ptsd flashbacks to my pre-med days. you got this though! ⚗️",
      created_at: "2024-01-12T20:30:00Z",
      author: { id: "user17", handle: "recovering-pre-med" },
      schedule_id: "4",
    },
    {
      id: "c13",
      body: "anatomy & physiology on friday afternoon is rough but at least you can decompress over the weekend!",
      created_at: "2024-01-13T07:45:00Z",
      author: { id: "user18", handle: "bio-student-99" },
      schedule_id: "4",
    },
  ],
  "5": [
    {
      id: "c14",
      body: "this looks so manageable compared to my engineering schedule! psychology majors have it figured out 🧠",
      created_at: "2024-01-11T12:45:00Z",
      author: { id: "user19", handle: "envious-engineer" },
      schedule_id: "5",
    },
    {
      id: "c15",
      body: "cognitive psychology is my absolute favorite! dr. chen is an amazing professor. you'll love it!",
      created_at: "2024-01-11T15:20:00Z",
      author: { id: "user20", handle: "psych-enthusiast-42" },
      schedule_id: "5",
    },
  ],
}
