// Vercel serverless function for colleges endpoint
module.exports = function handler(req, res) {
  // Set CORS headers
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'GET, POST, PUT, DELETE, OPTIONS');
  res.setHeader('Access-Control-Allow-Headers', 'Content-Type, Authorization');

  if (req.method === 'OPTIONS') {
    res.status(200).end();
    return;
  }

  if (req.method !== 'GET') {
    return res.status(405).json({ error: 'Method not allowed' });
  }

  // Comprehensive college list - CSU, Arizona, Big State Colleges
  const colleges = [
    // California State Universities (CSU)
    { slug: "cal-poly-slo", name: "Cal Poly San Luis Obispo" },
    { slug: "cal-poly-pomona", name: "Cal Poly Pomona" },
    { slug: "csun", name: "California State University, Northridge" },
    { slug: "csulb", name: "California State University, Long Beach" },
    { slug: "csuf", name: "California State University, Fullerton" },
    { slug: "csusb", name: "California State University, San Bernardino" },
    { slug: "csusm", name: "California State University, San Marcos" },
    { slug: "csudh", name: "California State University, Dominguez Hills" },
    { slug: "csueb", name: "California State University, East Bay" },
    { slug: "csufresno", name: "California State University, Fresno" },
    { slug: "csuhayward", name: "California State University, Hayward" },
    { slug: "csul", name: "California State University, Los Angeles" },
    { slug: "csumb", name: "California State University, Monterey Bay" },
    { slug: "csus", name: "California State University, Sacramento" },
    { slug: "csusd", name: "California State University, San Diego" },
    { slug: "csusf", name: "California State University, San Francisco" },
    { slug: "csusj", name: "California State University, San Jose" },
    { slug: "csustan", name: "California State University, Stanislaus" },
    { slug: "csuchico", name: "California State University, Chico" },
    { slug: "csuhumboldt", name: "California State University, Humboldt" },
    { slug: "csumbakersfield", name: "California State University, Bakersfield" },
    { slug: "csuchannel-islands", name: "California State University, Channel Islands" },
    
    // Arizona Colleges
    { slug: "asu", name: "Arizona State University" },
    { slug: "uofa", name: "University of Arizona" },
    { slug: "nau", name: "Northern Arizona University" },
    { slug: "asu-tempe", name: "Arizona State University - Tempe" },
    { slug: "asu-poly", name: "Arizona State University - Polytechnic" },
    { slug: "asu-west", name: "Arizona State University - West" },
    { slug: "asu-downtown", name: "Arizona State University - Downtown Phoenix" },
    
    // Big State Colleges
    { slug: "rutgers", name: "Rutgers University" },
    { slug: "penn-state", name: "Penn State University" },
    { slug: "gsu", name: "Georgia State University" },
    { slug: "uga", name: "University of Georgia" },
    { slug: "texas-am", name: "Texas A&M University" },
    { slug: "ut-austin", name: "University of Texas at Austin" },
    { slug: "ufl", name: "University of Florida" },
    { slug: "fsu", name: "Florida State University" },
    { slug: "umich", name: "University of Michigan" },
    { slug: "msu", name: "Michigan State University" },
    { slug: "osu", name: "Ohio State University" },
    { slug: "uiuc", name: "University of Illinois at Urbana-Champaign" },
    { slug: "uw-madison", name: "University of Wisconsin-Madison" },
    { slug: "umn", name: "University of Minnesota" },
    { slug: "purdue", name: "Purdue University" },
    { slug: "indiana", name: "Indiana University" },
    { slug: "mizzou", name: "University of Missouri" },
    { slug: "kansas", name: "University of Kansas" },
    { slug: "oklahoma", name: "University of Oklahoma" },
    { slug: "arkansas", name: "University of Arkansas" },
    { slug: "lsu", name: "Louisiana State University" },
    { slug: "ole-miss", name: "University of Mississippi" },
    { slug: "alabama", name: "University of Alabama" },
    { slug: "auburn", name: "Auburn University" },
    { slug: "tennessee", name: "University of Tennessee" },
    { slug: "kentucky", name: "University of Kentucky" },
    { slug: "virginia-tech", name: "Virginia Tech" },
    { slug: "uva", name: "University of Virginia" },
    { slug: "ncsu", name: "North Carolina State University" },
    { slug: "unc", name: "University of North Carolina" },
    { slug: "clemson", name: "Clemson University" },
    { slug: "south-carolina", name: "University of South Carolina" },
    { slug: "maryland", name: "University of Maryland" },
    { slug: "delaware", name: "University of Delaware" },
    { slug: "west-virginia", name: "West Virginia University" },
    { slug: "pitt", name: "University of Pittsburgh" },
    { slug: "temple", name: "Temple University" },
    { slug: "drexel", name: "Drexel University" },
    { slug: "boston-u", name: "Boston University" },
    { slug: "northeastern", name: "Northeastern University" },
    { slug: "umass", name: "University of Massachusetts" },
    { slug: "uconn", name: "University of Connecticut" },
    { slug: "rhode-island", name: "University of Rhode Island" },
    { slug: "maine", name: "University of Maine" },
    { slug: "new-hampshire", name: "University of New Hampshire" },
    { slug: "vermont", name: "University of Vermont" },
    { slug: "buffalo", name: "University at Buffalo" },
    { slug: "binghamton", name: "Binghamton University" },
    { slug: "stony-brook", name: "Stony Brook University" },
    { slug: "albany", name: "University at Albany" },
    { slug: "syracuse", name: "Syracuse University" },
    { slug: "cornell", name: "Cornell University" },
    { slug: "columbia", name: "Columbia University" },
    { slug: "nyu", name: "New York University" },
    { slug: "fordham", name: "Fordham University" },
    { slug: "st-johns", name: "St. John's University" },
    { slug: "hofstra", name: "Hofstra University" },
    { slug: "adelphi", name: "Adelphi University" },
    { slug: "pace", name: "Pace University" },
    { slug: "manhattan", name: "Manhattan College" },
    { slug: "iona", name: "Iona University" },
    { slug: "marist", name: "Marist College" },
    { slug: "siena", name: "Siena College" },
    { slug: "union", name: "Union College" },
    { slug: "skidmore", name: "Skidmore College" },
    { slug: "bard", name: "Bard College" },
    { slug: "vassar", name: "Vassar College" },
    { slug: "hamilton", name: "Hamilton College" },
    { slug: "colgate", name: "Colgate University" },
    { slug: "rochester", name: "University of Rochester" },
    { slug: "rochester-tech", name: "Rochester Institute of Technology" },
    { slug: "nazareth", name: "Nazareth College" },
    { slug: "st-john-fisher", name: "St. John Fisher College" },
    { slug: "roberts-wesleyan", name: "Roberts Wesleyan College" },
    { slug: "houghton", name: "Houghton University" },
    { slug: "geneseo", name: "SUNY Geneseo" },
    { slug: "cortland", name: "SUNY Cortland" },
    { slug: "oswego", name: "SUNY Oswego" },
    { slug: "oneonta", name: "SUNY Oneonta" },
    { slug: "fredonia", name: "SUNY Fredonia" },
    { slug: "new-paltz", name: "SUNY New Paltz" },
    { slug: "purchase", name: "SUNY Purchase" },
    { slug: "old-westbury", name: "SUNY Old Westbury" },
    { slug: "farmingdale", name: "SUNY Farmingdale" },
    { slug: "maritime", name: "SUNY Maritime" },
    { slug: "cobleskill", name: "SUNY Cobleskill" },
    { slug: "morrisville", name: "SUNY Morrisville" },
    { slug: "delhi", name: "SUNY Delhi" },
    { slug: "canton", name: "SUNY Canton" },
    { slug: "potsdam", name: "SUNY Potsdam" },
    { slug: "plattsburgh", name: "SUNY Plattsburgh" },
    { slug: "binghamton", name: "SUNY Binghamton" },
    { slug: "buffalo", name: "SUNY Buffalo" },
    { slug: "albany", name: "SUNY Albany" },
    { slug: "stony-brook", name: "SUNY Stony Brook" },
    { slug: "downstate", name: "SUNY Downstate" },
    { slug: "upstate", name: "SUNY Upstate" },
    { slug: "optometry", name: "SUNY College of Optometry" },
    { slug: "environmental-science", name: "SUNY College of Environmental Science and Forestry" },
    { slug: "empire-state", name: "SUNY Empire State College" },
    { slug: "polytechnic", name: "SUNY Polytechnic Institute" },
    { slug: "rockland", name: "SUNY Rockland Community College" },
    { slug: "orange", name: "SUNY Orange County Community College" },
    { slug: "ulster", name: "SUNY Ulster County Community College" },
    { slug: "dutchess", name: "SUNY Dutchess Community College" },
    { slug: "westchester", name: "SUNY Westchester Community College" },
    { slug: "putnam", name: "SUNY Putnam County Community College" },
    { slug: "sullivan", name: "SUNY Sullivan County Community College" },
    { slug: "columbia-greene", name: "SUNY Columbia-Greene Community College" },
    { slug: "adirondack", name: "SUNY Adirondack Community College" },
    { slug: "clinton", name: "SUNY Clinton Community College" },
    { slug: "jefferson", name: "SUNY Jefferson Community College" },
    { slug: "mohawk-valley", name: "SUNY Mohawk Valley Community College" },
    { slug: "herkimer", name: "SUNY Herkimer County Community College" },
    { slug: "fulton-montgomery", name: "SUNY Fulton-Montgomery Community College" },
    { slug: "schenectady", name: "SUNY Schenectady County Community College" },
    { slug: "hudson-valley", name: "SUNY Hudson Valley Community College" },
    { slug: "adk", name: "SUNY Adirondack" },
    { slug: "broome", name: "SUNY Broome Community College" },
    { slug: "corning", name: "SUNY Corning Community College" },
    { slug: "finger-lakes", name: "SUNY Finger Lakes Community College" },
    { slug: "genesee", name: "SUNY Genesee Community College" },
    { slug: "jamestown", name: "SUNY Jamestown Community College" },
    { slug: "monroe", name: "SUNY Monroe Community College" },
    { slug: "niagara", name: "SUNY Niagara County Community College" },
    { slug: "north-country", name: "SUNY North Country Community College" },
    { slug: "onondaga", name: "SUNY Onondaga Community College" },
    { slug: "tompkins-cortland", name: "SUNY Tompkins Cortland Community College" },
    { slug: "wayne-finger-lakes", name: "SUNY Wayne Finger Lakes Community College" }
  ];

  res.status(200).json(colleges);
}
